version: '3'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    networks:
      - app-network

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    networks:
      - app-network
    deploy:
      replicas: 2

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
